// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/[...id].ts";
import * as $2 from "./routes/style.css.ts";
import * as $3 from "./routes/_render.ts";
import * as $4 from "./routes/[id]/1[path].tsx";
import * as $5 from "./routes/sitemap.ts";
import * as $6 from "./routes/api/joke.ts";
import * as $7 from "./routes/page.js.ts";
import * as $$0 from "./islands/LawList.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/[...id].ts": $1,
    "./routes/style.css.ts": $2,
    "./routes/_render.ts": $3,
    "./routes/[id]/1[path].tsx": $4,
    "./routes/sitemap.ts": $5,
    "./routes/api/joke.ts": $6,
    "./routes/page.js.ts": $7,
  },
  islands: {
    "./islands/LawList.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
