// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/[...id].tsx";
import * as $1 from "./routes/_render.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/page.js.ts";
import * as $4 from "./routes/sitemap.txt.ts";
import * as $5 from "./routes/style.css.ts";
import * as $$0 from "./islands/LawList.tsx";

const manifest = {
  routes: {
    "./routes/[...id].tsx": $0,
    "./routes/_render.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/page.js.ts": $3,
    "./routes/sitemap.txt.ts": $4,
    "./routes/style.css.ts": $5,
  },
  islands: {
    "./islands/LawList.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
