// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/[id].tsx";
import * as $1 from "./pages/index.tsx";
import * as $2 from "./pages/sitemap.ts";
import * as $3 from "./pages/api/list.ts";
import * as $4 from "./pages/[id]/[path].tsx";

const routes = {
  pages: {
    "./pages/[id].tsx": $0,
    "./pages/index.tsx": $1,
    "./pages/sitemap.ts": $2,
    "./pages/api/list.ts": $3,
    "./pages/[id]/[path].tsx": $4,
  },
  baseUrl: import.meta.url,
};

export default routes;
